openapi: "3.1.0"
info:
  title: "smart_lodge API"
  description: "smart_lodge API"
  version: "1.0.0"
servers:
- url: "https://smart_lodge"
paths:
  /fotoalbum:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Fotoalbum"
              examples:
                Example#1:
                  description: ""
                  value:
                    fotos: []
  /image/{imageName}:
    get:
      description: ""
      parameters:
      - name: "imageName"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK <br> A file response"
          content:
            application/*:
              schema:
                type: "object"
                format: "binary"
  /upload-images:
    post:
      description: ""
  /get-smart-home-measurements:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Measurement"
  /get-smart-home-measurment/{buildingID}:
    get:
      description: ""
      parameters:
      - name: "buildingID"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Measurement"
  /get-smart-homes:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/SmartHome"
  /user-info:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserInfo"
  /login:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FreeMarkerContent"
              examples:
                Example#1:
                  description: ""
                  value:
                    template: "login.ftl"
                    model: "null"
                    etag: "null"
                    contentType: "null"
    post:
      description: ""
      responses:
        "302":
          description: "Found <br> Redirect"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "/"
  /logout:
    get:
      description: ""
      responses:
        "302":
          description: "Found <br> Redirect"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  description: ""
                  value: "/login"
components:
  schemas:
    Foto:
      type: "object"
      properties:
        url:
          type: "string"
        name:
          type: "string"
      required:
      - "url"
      - "name"
    Fotoalbum:
      type: "object"
      properties:
        fotos:
          type: "array"
          items:
            $ref: "#/components/schemas/Foto"
      required:
      - "fotos"
    Measurement:
      type: "object"
      properties:
        timeStamp:
          type: "string"
        buildingID:
          type: "string"
        brightness:
          type: "integer"
          format: "int32"
        temperature:
          type: "integer"
          format: "int32"
        humidity:
          type: "integer"
          format: "int32"
        gas:
          type: "integer"
          format: "int32"
      required:
      - "timeStamp"
      - "buildingID"
      - "brightness"
      - "temperature"
      - "humidity"
      - "gas"
    SmartHome:
      type: "object"
      properties:
        buildingID:
          type: "string"
      required:
      - "buildingID"
    UserInfo:
      type: "object"
      properties:
        username:
          type: "string"
      required:
      - "username"
    Object:
      type: "object"
      properties: {}
    HeaderValueParam:
      type: "object"
      properties:
        name:
          type: "string"
        value:
          type: "string"
        escapeValue:
          type: "boolean"
      required:
      - "name"
      - "value"
      - "escapeValue"
    ContentType:
      type: "object"
      properties:
        contentType:
          type: "string"
        contentSubtype:
          type: "string"
        parameters:
          type: "array"
          items:
            $ref: "#/components/schemas/HeaderValueParam"
      required:
      - "contentType"
      - "contentSubtype"
      - "parameters"
    FreeMarkerContent:
      type: "object"
      properties:
        template:
          type: "string"
        model:
          $ref: "#/components/schemas/Object"
        etag:
          type: "string"
        contentType:
          $ref: "#/components/schemas/ContentType"
      required:
      - "template"
      - "contentType"