/**
 * smart_lodge API
 * smart_lodge API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("fotoalbumGet", () => {
    return expect(instance.fotoalbumGet({})).resolves.toBe(null)
  })
  test("imageImageNameGet", () => {
    const imageName: any = undefined
    return expect(instance.imageImageNameGet(imageName, {})).resolves.toBe(null)
  })
  test("loginGet", () => {
    return expect(instance.loginGet({})).resolves.toBe(null)
  })
  test("loginPost", () => {
    return expect(instance.loginPost({})).resolves.toBe(null)
  })
  test("logoutGet", () => {
    return expect(instance.logoutGet({})).resolves.toBe(null)
  })
  test("uploadImagesPost", () => {
    return expect(instance.uploadImagesPost({})).resolves.toBe(null)
  })
  test("userInfoGet", () => {
    return expect(instance.userInfoGet({})).resolves.toBe(null)
  })
})

